name: Continuous Integration

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  lint-and-build:
    name: Lint and Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.25.x
          cache-dependency-path: "go.sum"

      - name: Run linters
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.4.0
          args: --config ./.golangci.yaml

      - name: Install TinyGo
        run: |
          wget https://github.com/tinygo-org/tinygo/releases/download/v0.39.0/tinygo_0.39.0_amd64.deb
          sudo dpkg -i tinygo_0.39.0_amd64.deb

      - name: Build Artifacts
        run: |
          make all -j $(nproc)
